export enum ProjectRole {
    DEVELOPER = "DEVELOPER",
    SCRUM_MASTER = "SCRUM_MASTER",
    AGILE_SCRUM_PROJECT_MANAGER = "AGILE_SCRUM_PROJECT_MANAGER",
    ASST_SCRUM_MASTER = "ASST_SCRUM_MASTER"
}
